### ISSUE TITLE
Add .gitignore

### ISSUE THREAD

**Issue by mats-claassen** [EurekaCommunity/VideoRow#1]
Hi @Smiller193, Thanks for doing this!

You should add a `gitignore` file to the repository to avoid uploading certain files, including the Pod dependencies. 

A good example of `gitignore` for Swift is [here](https://github.com/github/gitignore/blob/master/Swift.gitignore)

After that you must forcefully remove the files that should be ignored but have already been pushed to this repo. You can follow [this thread](https://stackoverflow.com/questions/7927230/remove-directory-from-remote-repository-after-adding-them-to-gitignore) to do that.

**Comment by Smiller193** [comment]
@mats-claassen how do i know which files to be removed without messing up the repo

**Comment by SebastianBO** [comment]
Nice upload @Smiller193

**Comment by mats-claassen** [comment]
It looks good now. One thing missing is the Pods.xcodeproj in the root folder which is a link. This could be removed.

**Comment by Smiller193** [comment]
is it still there? @mats-claassen and if it is what would I add to remove that

**Comment by mats-claassen** [comment]
Opened a PR #3

**Comment by Smiller193** [comment]
okay I merged the PR request. should I close this now? @mats-claassen ill fix the read me when I get off of work.

**Comment by Smiller193** [comment]
@mats-claassen read me is updated
